/** @type {import('tailwindcss').Config} */

// Helper to build a color that reads space-separated RGB channels from a CSS var,
// while still supporting Tailwind's opacity suffixes (e.g. bg-surface/60).
const withVar = (name) => `rgb(var(${name}) / <alpha-value>)`;

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Apple (light mode) colors
        apple: {
          primary: withVar('--color-apple-primary'),
          'primary-focus': withVar('--color-apple-primary-focus'),
          'primary-dark': withVar('--color-apple-primary-dark'),
          ink: withVar('--color-apple-ink'),
          body: withVar('--color-apple-body'),
          'body-dark': withVar('--color-apple-body-dark'),
          'body-muted': withVar('--color-apple-body-muted'),
          'ink-muted-80': withVar('--color-apple-ink-muted-80'),
          'ink-muted-48': withVar('--color-apple-ink-muted-48'),
          'divider-soft': withVar('--color-apple-divider-soft'),
          hairline: withVar('--color-apple-hairline'),
          canvas: withVar('--color-apple-canvas'),
          'canvas-parchment': withVar('--color-apple-canvas-parchment'),
          'surface-pearl': withVar('--color-apple-surface-pearl'),
          'surface-tile-1': withVar('--color-apple-surface-tile-1'),
          'surface-tile-2': withVar('--color-apple-surface-tile-2'),
          'surface-tile-3': withVar('--color-apple-surface-tile-3'),
          'surface-black': withVar('--color-apple-surface-black'),
          'surface-chip-translucent': withVar('--color-apple-surface-chip-translucent'),
          'on-primary': withVar('--color-apple-on-primary'),
        },
        // Cursor (dark mode) colors
        cursor: {
          primary: withVar('--color-cursor-primary'),
          'primary-active': withVar('--color-cursor-primary-active'),
          ink: withVar('--color-cursor-ink'),
          body: withVar('--color-cursor-body'),
          'body-strong': withVar('--color-cursor-body-strong'),
          muted: withVar('--color-cursor-muted'),
          'muted-soft': withVar('--color-cursor-muted-soft'),
          hairline: withVar('--color-cursor-hairline'),
          'hairline-soft': withVar('--color-cursor-hairline-soft'),
          'hairline-strong': withVar('--color-cursor-hairline-strong'),
          canvas: withVar('--color-cursor-canvas'),
          'canvas-soft': withVar('--color-cursor-canvas-soft'),
          'surface-card': withVar('--color-cursor-surface-card'),
          'surface-strong': withVar('--color-cursor-surface-strong'),
          'on-primary': withVar('--color-cursor-on-primary'),
          'timeline-thinking': withVar('--color-cursor-timeline-thinking'),
          'timeline-grep': withVar('--color-cursor-timeline-grep'),
          'timeline-read': withVar('--color-cursor-timeline-read'),
          'timeline-edit': withVar('--color-cursor-timeline-edit'),
          'timeline-done': withVar('--color-cursor-timeline-done'),
          error: withVar('--color-cursor-error'),
          success: withVar('--color-cursor-success'),
        },
        // Legacy colors
        bg: withVar('--color-bg'),
        surface: withVar('--color-surface'),
        'surface-2': withVar('--color-surface-2'),
        'surface-3': withVar('--color-surface-3'),
        border: withVar('--color-border'),
        'border-strong': withVar('--color-border-strong'),
        accent: withVar('--color-accent'),
        'accent-2': withVar('--color-accent-2'),
        'accent-contrast': withVar('--color-accent-contrast'),
        info: withVar('--color-info'),
        success: withVar('--color-success'),
        warning: withVar('--color-warning'),
        danger: withVar('--color-danger'),
        'text-primary': withVar('--color-text-primary'),
        'text-secondary': withVar('--color-text-secondary'),
        'text-muted': withVar('--color-text-muted'),
        focus: withVar('--color-focus'),
        'grid-line': withVar('--grid-line'),
      },
      fontFamily: {
        'apple-display': ['SF Pro Display', 'Inter', 'system-ui', '-apple-system', 'sans-serif'],
        'apple-body': ['SF Pro Text', 'Inter', 'system-ui', '-apple-system', 'sans-serif'],
        'cursor-display': ['system-ui', '"Helvetica Neue"', 'Helvetica', 'Arial', 'sans-serif'],
        'cursor-body': ['system-ui', '"Helvetica Neue"', 'Helvetica', 'Arial', 'sans-serif'],
        display: ['General Sans', 'Satoshi', 'Clash Display', 'Space Grotesk', 'Inter', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
        data: ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      borderRadius: {
        'apple-none': '0px',
        'apple-xs': '5px',
        'apple-sm': '8px',
        'apple-md': '11px',
        'apple-lg': '18px',
        'apple-pill': '9999px',
        'cursor-xs': '4px',
        'cursor-sm': '6px',
        'cursor-md': '8px',
        'cursor-lg': '12px',
        'cursor-xl': '16px',
        'cursor-pill': '9999px',
        xs: '4px',
        sm: '6px',
        md: '8px',
        lg: '12px',
        xl: '18px',
        '2xl': '24px',
        full: '9999px',
        card: '12px',
        button: '8px',
      },
      fontSize: {
        // Apple typography
        'apple-hero-display': ['56px', { lineHeight: '1.07', letterSpacing: '-0.28px', fontWeight: '600' }],
        'apple-display-lg': ['40px', { lineHeight: '1.1', letterSpacing: '0', fontWeight: '600' }],
        'apple-display-md': ['34px', { lineHeight: '1.47', letterSpacing: '-0.374px', fontWeight: '600' }],
        'apple-lead': ['28px', { lineHeight: '1.14', letterSpacing: '0.196px', fontWeight: '400' }],
        'apple-lead-airy': ['24px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '300' }],
        'apple-tagline': ['21px', { lineHeight: '1.19', letterSpacing: '0.231px', fontWeight: '600' }],
        'apple-body-strong': ['17px', { lineHeight: '1.24', letterSpacing: '-0.374px', fontWeight: '600' }],
        'apple-body': ['17px', { lineHeight: '1.47', letterSpacing: '-0.374px', fontWeight: '400' }],
        'apple-dense-link': ['17px', { lineHeight: '2.41', letterSpacing: '0', fontWeight: '400' }],
        'apple-caption': ['14px', { lineHeight: '1.43', letterSpacing: '-0.224px', fontWeight: '400' }],
        'apple-caption-strong': ['14px', { lineHeight: '1.29', letterSpacing: '-0.224px', fontWeight: '600' }],
        'apple-button-lg': ['18px', { lineHeight: '1.0', letterSpacing: '0', fontWeight: '300' }],
        'apple-button-utility': ['14px', { lineHeight: '1.29', letterSpacing: '-0.224px', fontWeight: '400' }],
        'apple-fine-print': ['12px', { lineHeight: '1.0', letterSpacing: '-0.12px', fontWeight: '400' }],
        'apple-micro-legal': ['10px', { lineHeight: '1.3', letterSpacing: '-0.08px', fontWeight: '400' }],
        'apple-nav-link': ['12px', { lineHeight: '1.0', letterSpacing: '-0.12px', fontWeight: '400' }],
        // Cursor typography
        'cursor-display-mega': ['72px', { lineHeight: '1.1', letterSpacing: '-2.16px', fontWeight: '400' }],
        'cursor-display-lg': ['36px', { lineHeight: '1.2', letterSpacing: '-0.72px', fontWeight: '400' }],
        'cursor-display-md': ['26px', { lineHeight: '1.25', letterSpacing: '-0.325px', fontWeight: '400' }],
        'cursor-display-sm': ['22px', { lineHeight: '1.3', letterSpacing: '-0.11px', fontWeight: '400' }],
        'cursor-title-md': ['18px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '600' }],
        'cursor-title-sm': ['16px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '600' }],
        'cursor-body-md': ['16px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'cursor-body-tracked': ['16px', { lineHeight: '1.5', letterSpacing: '0.08px', fontWeight: '400' }],
        'cursor-body-sm': ['14px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'cursor-caption': ['13px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '400' }],
        'cursor-caption-uppercase': ['11px', { lineHeight: '1.4', letterSpacing: '0.88px', fontWeight: '600', textTransform: 'uppercase' }],
        'cursor-code': ['13px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'cursor-button': ['14px', { lineHeight: '1.0', letterSpacing: '0', fontWeight: '500' }],
        'cursor-nav-link': ['14px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '500' }],
        // Legacy font sizes
        xs: ['0.75rem', { lineHeight: '1rem' }],
        sm: ['0.875rem', { lineHeight: '1.25rem' }],
        'body-sm': ['0.875rem', { lineHeight: '1.25rem' }],
        label: ['0.75rem', { lineHeight: '1rem', fontWeight: '600' }],
      },
      spacing: {
        'apple-xxs': '4px',
        'apple-xs': '8px',
        'apple-sm': '12px',
        'apple-md': '17px',
        'apple-lg': '24px',
        'apple-xl': '32px',
        'apple-xxl': '48px',
        'apple-section': '80px',
        'cursor-xxs': '4px',
        'cursor-xs': '8px',
        'cursor-sm': '12px',
        'cursor-base': '16px',
        'cursor-md': '20px',
        'cursor-lg': '24px',
        'cursor-xl': '32px',
        'cursor-xxl': '48px',
        'cursor-section': '80px',
      },
      minHeight: {
        control: '2.5rem',
      },
      height: {
        control: '2.5rem',
      },
      width: {
        control: '2.5rem',
      },
      boxShadow: {
        xs: '0 1px 2px rgba(0, 0, 0, 0.35)',
        sm: '0 2px 8px rgba(0, 0, 0, 0.28)',
        card: '0 8px 24px rgba(0, 0, 0, 0.24)',
        elevated: '0 18px 48px rgba(0, 0, 0, 0.42)',
        focus: '0 0 0 3px rgba(201, 145, 52, 0.3)',
      },
    },
  },
  plugins: [],
}
